name: "Install Graphviz on Runners"
description: "Installs Graphviz on various operating systems."

branding:
  icon: arrow-down-circle
  color: purple

runs:
  using: "composite"
  steps:
    - id: install-graphviz-macos
      name: Install Graphviz on MacOS
      if: runner.os == 'macOS'
      shell: bash
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
      run: |
        # Install Graphviz on MacOS
        # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew info graphviz
        brew install graphviz
    - id: install-graphviz-windows
      name: Install Graphviz on Windows
      if: runner.os == 'Windows'
      shell: bash
      run: |
        # Install Graphviz on Linux
        choco install graphviz
    - id: install-graphviz-linux
      name: Install Graphviz on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # Install Graphviz on Linux
        sudo apt-get install graphviz
    - id: check-graphviz
      name: Check Graphviz
      if: ${{ success() }
      shell: bash
      run: |
        # Check Graphviz
        echo "`dot -V` installed successfully on ${{ runner.os }}"
