name: Test Install Graphviz

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  install:
    name: Install Graphviz
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

# TEST INSTALL GRAPHVIZ
    - id: install-graphviz
      name: Install Graphviz
      uses: sualeh/install-graphviz@main

    - id: test-install-graphviz
      name: Test Install Graphviz
      shell: bash
      run: |
        # Test Install Graphviz
        echo "Test Graphviz install"
        dot -V
